# Generated by Django 5.2.15 on 2026-06-25 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="disclosurerule",
            name="field_name",
            field=models.CharField(
                choices=[
                    ("identity_name", "Identity Name"),
                    ("display_name", "Display Name"),
                    ("description", "Description"),
                ],
                default="display_name",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="disclosurerule",
            name="is_visible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="context_category",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("personal", "Personal"),
                    ("family", "Family"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="disclosurerule",
            unique_together={("identity", "relationship_type", "field_name")},
        ),
        migrations.AlterUniqueTogether(
            name="relationship",
            unique_together={("owner", "target_user")},
        ),
    ]
