# Generated by Django 5.2.15 on 2026-08-09 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("provider_uid", models.CharField(max_length=255)),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_uid"), name="unique_provider_uid"
                    ),
                    models.UniqueConstraint(
                        fields=("user", "provider"), name="unique_user_provider"
                    ),
                ],
            },
        ),
    ]
