# Generated by Django 5.2.15 on 2026-08-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0002_linkedaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disclosurerule",
            name="field_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="identityattribute",
            unique_together={("identity", "key")},
        ),
    ]
