# Generated by Django 5.2.15 on 2026-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0003_alter_disclosurerule_field_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identityattribute",
            name="value",
            field=models.JSONField(null=True),
        ),
    ]
