# Generated by Django 5.2.15 on 2026-09-09 07:24

import identities.security.token_encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0004_alter_identityattribute_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkedaccount",
            name="access_token",
            field=identities.security.token_encryption.EncryptedCharField(
                blank=True, max_length=512, null=True
            ),
        ),
        migrations.AlterField(
            model_name="linkedaccount",
            name="refresh_token",
            field=identities.security.token_encryption.EncryptedCharField(
                blank=True, max_length=512, null=True
            ),
        ),
    ]
