# Generated by Django 5.2.15 on 2026-09-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='is_public_default',
            new_name='is_system',
        ),
    ]
