# Generated by Django 5.2.15 on 2026-09-11 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0007_rename_is_public_default_context_is_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='context',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('owner',), name='unique_system_context_per_owner'),
        ),
    ]
