# Generated by Django 5.2.15 on 2026-09-12 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0009_connectionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='connectionrequest',
            name='unique_connection_request_per_pair',
        ),
        migrations.AddConstraint(
            model_name='connectionrequest',
            constraint=models.UniqueConstraint(fields=('sender', 'recipient'), name='unique_connection_request_per_pair'),
        ),
    ]
