from .views import home_view, dashboard_view, profile_redirect_view, profile_view
from .auth_views import WebLoginView, WebLogoutView, register_view
# from .context_views import ...        # add as these get built out
# from .identity_views import ...
# from .relationship_views import ...
# from .disclosure_views import ...
# from .integration_views import ...