from .views import home_view, dashboard_view, profile_redirect_view, profile_view
from .auth_views import WebLoginView, WebLogoutView, register_view
from .context_views import (
    context_list_view, context_create_view, context_delete_view, context_edit_view
)# from .identity_views import ...
# from .relationship_views import ...
# from .disclosure_views import ...
# from .integration_views import ...